### ISSUE TITLE
Manifest entry referencing a COM object should point to required interface.

### ISSUE THREAD

**Issue by chendrixson** [MicrosoftDocs/winrt-related#100]
The manifest entry points to a GUID, but we should also link out to the Interface the that thumbnail handler would need to implement to get this working E2E.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af19dcfd-7147-5b7c-0784-db051145184b
* Version Independent ID: be2ace2f-05cb-b892-76cc-f78da65f488b
* Content: [desktop2:ThumbnailHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-thumbnailhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-thumbnailhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-thumbnailhandler.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
