### ISSUE TITLE
Load Images from embedded resources for Desktop Applications

### ISSUE THREAD

**Issue by homer90** [MicrosoftDocs/winrt-related#104]
Desktop apps should be able to show toast notifications with embedded resource images.
Right now every image that is used in a toast notifiction has to be stored on disk for usage with file:///

But many applications pack their images within embedded resources:
&lt;ItemGroup&gt;
    &lt;EmbeddedResource Include="Images\*" /&gt;
&lt;/ItemGroup&gt;

Loading images from embedded resources (e.g. resource:///) would eliminate the need for desktop apps to store their images on disk for toast notifications.

The same question also appeared some time ago on Stack Overflow:
https://stackoverflow.com/questions/41570815/using-image-from-app-package-in-win10-toast

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6e0613-f0ef-682b-376c-0e56077f8c63
* Version Independent ID: 7a9667c6-af0e-9ef8-f999-ce942cb02c9e
* Content: [image - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-image)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/element-image.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/element-image.md)
* Product: **uwp**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
