### ISSUE TITLE
Add a new "App lifecycle" section with useful APIs for Win32 devs

### ISSUE THREAD

**Issue by Sergio0694** [MicrosoftDocs/winrt-related#122]
One major issue for Win32 devs working on UWP apps is the way the OS handles the lifecycle of UWP apps.
Specifically, by default, Windows "tombstones" UWP apps as soon as they are minimized, eventually suspending them and forcing them to reinitialize their UI and more whenever the user bring them up again.
This is useful for users running on portable devices or notebooks, but not ideal for advanced users working on Desktops.
A solution for this is to use the Extended Execution API (https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-minimized-with-extended-execution), which lets UWP apps remain active when minimized or under lock screen.

This is just an example of a feature that's often crucial for Win32 devs (that take for granted that their app won't have to deal with the OS suspending it on its own), but that's difficult to find for new UWP devs, unless they know exactly what they're looking for.

I think it'd be a good idea to add this new "App lifecycle" section with a description/link to this API, as well as other APIs that might be useful for Win32 devs new to the UWP platform (others are welcome to chime in with ideas).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4b0781-eddc-d60c-db62-5e2e50ffad6a
* Version Independent ID: 0c885553-52a1-a380-e6be-adeeab59d367
* Content: [Alternatives to Windows APIs in Universal Windows Platform (UWP) apps - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/win32-and-com/alternatives-to-windows-apis-uwp#feedback)
* Content Source: [winrt-related-src/win32-and-com/alternatives-to-windows-apis-uwp.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/win32-and-com/alternatives-to-windows-apis-uwp.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by dpaulino** [comment]
I'd like to throw my 2 cents here as well. I've spoken with several uwp devs who ask for this type of feature (disabling tombstoning or somehow postponing it) and for the past 2 years I unfortunately had no response. It would have been very helpful to know about this feature as soon as it became available, instead of learning about this feature this week.

Adding this app lifecycle section and mentioning the extended execution API would help a lot of devs learn that they can get around the tombstoning if they wanted. Please consider adding this section.

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you, @dpaulino, or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
