### ISSUE TITLE
Missing documentation for winrt::guid

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/winrt-related#128]
The `guid` type in namespace `winrt` is currently undocumented. I'm looking for documentation, that allows me to answer the following questions:

* Why should I use `winrt::guid` instead of [`GUID`](https://docs.microsoft.com/en-us/previous-versions/aa373931(v%3Dvs.80))?
* How do I convert between the two?
* How do I construct a `winrt::guid`?
* Which header file(s) do I need to include?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36b3f5b-e729-300a-eb81-402648520ff3
* Version Independent ID: 40daa692-e9a1-2e27-0c10-c6baf69bc453
* Content: [winrt namespace (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/winrt)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/winrt.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/winrt.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tim-weis. I realize that there's not yet a topic for **winrt::guid** in the [reference content](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/winrt), but it's on my backlog. Meanwhile, here's some info, which I hope will help.

> Why should I use winrt::guid instead of GUID?

Because it will appear in the APIs you consume (and author). **winrt::guid** is C++/WinRT's projection of the GUID type. It also provides equality and inequality operators, constructors, and a conversion operator to GUID. For more info you can search for "winrt::guid" in this section: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/news#news-and-changes-in-windows-sdk-version-100177630-windows-10-version-1809. You can see more if you search for "struct guid" in winrt/base/h.

> How do I convert between the two?
> How do I construct a winrt::guid?

See above.

> Which header file(s) do I need to include?

To use winrt::guid, the usual approach to headers applies as described in [Get started](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/get-started). Specifically, you just include the appropriate header for the Windows Runtime namespaces you'll be using (for example, winrt/Windows.Foundation.h), and you'll get all the headers you need, including an implicit include of base.h. If you don't include any namespace headers at all, then manually `#include <winrt/base.h>`.

I'll close this for now, and track my backlog internally. Thanks! ~Steve

**Comment by tim-weis** [comment]
That's helpful information, thank you. I needed to construct a `winrt::guid` so was hoping to see the c'tor signature(s). While `winrt::guid` does provide a user-defined c'tor, it appears that the same syntax for direct initialization can be used as if it were a `GUID` struct.

**Comment by stevewhims** [comment]
Great, thanks, Tim!
