### ISSUE TITLE
Can any of these be modified upon app startup?

### ISSUE THREAD

**Issue by JosephClampett** [MicrosoftDocs/winrt-related#129]
For example, could BackgroundColor be changed *before* the app startup splash screen appears to change based on whether the current theme is dark or light?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 415ae1d9-f292-b920-3206-0c88489ba54c
* Version Independent ID: 011fd0bd-641d-7444-2f8e-00fe8195b42e
* Content: [uap:VisualElements (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-visualelements)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-visualelements.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-visualelements.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
