### ISSUE TITLE
What is a `Windows Shell BannersHandler`?

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/winrt-related#139]
Searching the web the only occurences are this documentation. Behind the link *Creating Shell Extensions Handlers* under *See also* there is also no mention of Banners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c820215-8733-f658-f0eb-2df7512da794
* Version Independent ID: 983095a1-2aa3-3026-62e7-ed67fff04e19
* Content: [desktop3:BannersHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop3-bannershandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop3-BannersHandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop3-BannersHandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.

**Comment by AliveDevil** [comment]
Still relevant.
Its unclear what
* CustomStateHandler
* ThumbnailProviderHandler
* ExtendedPropertyHandler
* BannersHandler
* ContentUriSource

map to in terms of COM-interfaces.
The [cloud-mirror-Sample](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/CloudMirror) doesn't even include `ExtendedPropertyHandler` and `BannersHandler`. Please provide proper guidance for implementation here.
