### ISSUE TITLE
No Sample!

### ISSUE THREAD

**Issue by NickWPF** [MicrosoftDocs/winrt-related#165]
ExtendedPropertyHandler

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c33df8fc-106a-af97-d949-93be15e27829
* Version Independent ID: c930f70c-8378-02d1-8c9f-68b1f985214d
* Content: [desktop3:ExtendedPropertyHandler - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/schemas/appxpackage/uapmanifestschema/element-desktop3-extendedpropertyhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop3-ExtendedPropertyHandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop3-ExtendedPropertyHandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
