### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-related#184]
Most contracts refer to a single particular type or API that they make available. This page should include, for each contract, a link to the type/API that is enabled by the contract

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e4929c-6492-6cdc-c59a-bb2ce1954151
* Version Independent ID: 1ce4ade6-ec7d-c3ee-a5dc-95dbf90cb9e9
* Content: [Windows Desktop Extension SDK API contracts for UWP - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-desktop-extension-sdk)
* Content Source: [winrt-related-src/extension-sdks/windows-desktop-extension-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-desktop-extension-sdk.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @asklar, and thanks for filing this issue. It sounds like the ask is this: take the list of API contract versions in each Extension SDK version and expand it out to a topic-per-API-contract-version. And then on the topic that documents each API-contract-version, render a hyperlinked list of APIs (linking to the individual API topics).

The way things stand, I can go ahead and make a note of this work item on my backlog. However, I'm unable to give you an estimated schedule around when or whether we'd be able to implement the feature.

I'll leave the issue open for a little while in case you want to reply. But since I'm tracking the request internally, we don't need to track it here.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close now, since we're tracking internally.
