### ISSUE TITLE
What happened to ForegroundText color property?

### ISSUE THREAD

**Issue by groovykool** [MicrosoftDocs/winrt-related#191]
What happened to ForegroundText color property?
How do set the app tile text to light or dark?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 415ae1d9-f292-b920-3206-0c88489ba54c
* Version Independent ID: 011fd0bd-641d-7444-2f8e-00fe8195b42e
* Content: [uap:VisualElements (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-visualelements)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-visualelements.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-visualelements.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate your suggestions. Though this issue will be marked as Closed, this issue is still being tracked internally and you're welcome to leave a comment with more details. Thank you again!
