### ISSUE TITLE
Universal device family API contracts page is missing SDK 19041

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-related#204]
[This page](https://docs.microsoft.com/uwp/extension-sdks/windows-universal-sdk) is missing information about the latest Windows 10 SDK 19041.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afdf49d-a4d3-2c25-5146-a74b31e45819
* Version Independent ID: 658615f6-b07b-3186-d042-6fb4b52e0640
* Content: [Universal device family API contracts - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk)
* Content Source: [winrt-related-src/extension-sdks/windows-universal-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-universal-sdk.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @chingucoding, and thanks for filing this issue. Yes, that topic isn't up to date. I've created a work item for myself, so I'll use that to track the work, and I'll go ahead and close this issue. I'll update this thread when I get around to working on the topic.

Thanks!
Steve

**Comment by marcelwgn** [comment]
Awesome, thanks for the heads up. Please feel free to comment here once the documentation has been updated! 😄

**Comment by stevewhims** [comment]
Hi, @chingucoding, I'm just reactivating this to ask whether you could help me understand the use case (or use cases) that you have for this topic. Specifically, how would you express what question (or questions) you need answering that visiting this topic helps answer?

Is it possible that you'd get the same info from visiting an API topic? For example, if you were using the [Uri class](https://docs.microsoft.com/uwp/api/windows.foundation.uri), and you looked in the "Windows 10 requirements" section for the values for "Device family" and "API contract", would that info answer the same question equally well?

Many thanks!
Steve

**Comment by marcelwgn** [comment]
Hi Steve,

There are 2 things why I am interested in this page:
1. [I wrote an app](https://github.com/chingucoding/UWP-Resources-Gallery) that has a dedicated page that lists the windows 10 builds and the corresponding contracts, in addition to code samples that you can copy in your app. When I tried to add the latest SDK (19041) I noticed that that isn't listed there anymore, thus I wasn't sure what to do here. 
2. While the pages of each property tell you what contract can be used to detect their presence, this is missing on the class itsself. For example, the `TintLuminosityOpacity` of the Acrylicbrush is only listed as being present with SDK 18362 on [this page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.acrylicbrush?view=winrt-19041), and I didn't know until I checked out the page for that property, which contract I could use here. Given that I already knew what that property does, it didn't really occur to me to even the page for that property, but I rather opened the documentation for the SDK contracts to find the appropriate one. In the case of AcrylicBrush it might be fine to just open the page of that property, however in the case of [NavigationView](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview?view=winrt-19041) the version history is quite lengthy, and just looking the SDK contracts up on a single page is easier than opening them for every different SDK in that list.

My main reason why I opened this issue is, that SDK 19041 is simply missing from that list, and that I am not 100% sure how those contracts would look like. 

So in the end, I would expect this page to be something I can simply lookup an SDK version and see which contract I can use to filter for that SDK, and which contracts are present on that SDK version (e.g. can I use Windows.MachineLearning on SDK version 10.0.16299.0).

I hope this information helps.

**Comment by stevewhims** [comment]
Hi, @chingucoding, and thanks for your reply, I do appreciate the info!

So, the recent history of this topic (and its sibling topics) is that we surveyed some customers and we found no compelling use cases for the info. That's why I wanted to check again before I remove the content.

1. I see, and I realize that missing or incomplete info in these topics is an inconvenience for your app. But it's also important for me to prioritize the needs of developer customers in general, and invest my resources in publishing and maintaining info that will give most developers the most value. As you know, I'm trying to gather info about any use case (or use cases) that people have for this topic (and its sibling topics). For you, the answer is that you use the info in your app for other develepers to see. So the question really then shifts to "what do the users of your app use that info for?" In other words, how would you express what question (or questions) you believe that the users of your app need answering that this particular info helps answer?
2. Isn't it true, though, that when we're writing code, we're always using some member (property, method, etc.) of a class? We can't use a class in the abstract, but rather we're always using a class through one of its members. We need to know what code to write to check for the presence of the member we want to access, so knowing what API contract introduced that member is useful. If the member is present, then the class must also be present. If the member is not present, then it's still possible that some other member(s) of the class are present, so even a binary "the class is there or it isn't" doesn't tell us which class members are or are not present. So I'd say that knowing what API contract the class itself is in doesn't help you to write adaptive code to consume the class's members.

Some good use cases for item 1 above would help me understand why we should preserve (and maintain and add to) this set of topics. But without those, it's looking like my best course of action here is to remove the topics that list API contracts. Again, I realize that that will affect your app.

Thanks again!
Steve

**Comment by marcelwgn** [comment]
Thank you for detailed reply @stevewhims !

Regarding point 1, I would say the main benefit with my app was, that people were able to say "I need contract X", and they would also be able to simply copy paste the C#/XAML code needed to check for that contract. Especially with the Universal Contracts, which map to the SDK versions, it was very neat to simply copy paste the check needed or lookup what contract is needed to check against specific SDKs.

Edit: Maybe those snippets is something that the documentation could provide instead of just saying "need Universal API Contract 5"? There is little to no benefit having to lookup how to query for a contract, and when using those features, almost certainly developers will need to query for that specific contract. Having that snippet already there probably makes it easier for developers.

However, you are totally right with point 2. There probably is a very small group of people who would know from the top of their head what contract or version they need, while almost everybody else would look that up in the specific API documentation. Though, at least for me, I know that specific features were added with specific Windows versions (e.g. CornerRadius with RS5), so I would just look the contract for RS5 up instead of searching for CornerRadius.

Overall, I agree with your assessment here. Given that the API contract needed for specific features is already documented in their API page, there is little to no benefit in having a separate site for these contracts. I think the best strategy is probably to remove that page altogether. Regarding my app, I will probably either remove that page too or at least remove the contracts since there is also limited value in how those are portrayed there as you already mentioned in item 2.

I hope this thread didn't cause any inconveniences for you, and if there is anything I can help with, feel free to let me know. Should I rename this issue then to "Remove Universal API list page" or something similiar as this will be the new direction moving forward in this area?

**Comment by stevewhims** [comment]
Thanks, @chingucoding, that sounds great. No need to rename this issue. I have a work item to do the necessary work, so I'll use that for tracking (and I hope to get to that soon). So for this issue, I'll go ahead and close it.

Thanks again!
-Steve
