### ISSUE TITLE
Add new settings ShowPrompt and UpdateBlocksActivation

### ISSUE THREAD

**Issue by JoeHaenf** [MicrosoftDocs/winrt-related#212]
As those settings can be used to describe an AppInstaller file, those should be documented here.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7ce943-631c-600e-c5ef-7ecd95f70aeb
* Version Independent ID: 95c6d06d-92c3-8900-e44f-8300644f12ee
* Content: [UpdateSettings - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings#feedback)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-update-settings.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-update-settings.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. ShowPrompt and UpdateBlocksActivation are attributes of the **OnLaunch** element. Therefore, they are documented in the [OnLaunch](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-onlaunch) article instead of [UpdateSettings](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings). 

If I have misunderstood your feedback, please feel free to reopen this issue with more info.
