### ISSUE TITLE
Describe newly released MSIX manifest schemas

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winrt-related#230]
These files were published in https://github.com/microsoft/msix-packaging/pull/433.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c20a74-18a7-a0a3-b828-6d2749151255
* Version Independent ID: 1ac0dc95-48ec-4a3b-4455-b8a0b6f094b2
* Content: [Package manifest schema reference for Windows 10 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
I have added documentation for the changes listed in the linked commit, except where noted.

NEW files:

cloudFiles extension – New version of desktop3:cloudFiles element. Created docs for this extension.
uap11 – No extension, just ManganeseAttributesGroup which are documented in each of the extension that reference them
com4 – documented: [com4:Extension - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com4-extension)
desktop7 – documented: [desktop7:Extension (in Package/Applications) - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension) AND [desktop7:Extension (in Package/Extensions) - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-package-extension)
PreviewManifestSchema_MsixAppCompatSupport_v3.xsd – Documented in non-preview schemas
•	[desktop8:UserMutablePackageDirectories - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop8-usermutablepackagedirectories)
•	[desktop7:SystemFileAssociation - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-systemfileassociation)
•	[desktop8:EventTracing - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop8-eventtracing)
•	[desktop8:UserMutablePackageDirectories - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop8-usermutablepackagedirectories)
uap12 - [uap12:Extension - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap12-extension)
VirtualizationManifestSchema.xsd – No top-level extension
•	[virtualization:ExcludedDirectories - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-virtualization-excludeddirectories)
•	[virtualization:ExcludedDirectory - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-virtualization-excludeddirectory)
•	[virtualization:ExcludedKey - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-virtualization-excludedkey)
•	[virtualization:ExcludedKeys - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-virtualization-excludedkeys)
•	[virtualization:FileSystemWriteVirtualization - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-virtualization-filesystemwritevirtualization)
•	[virtualization:RegistryWriteVirtualization - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-virtualization-registrywritevirtualization)
Desktop8 - [desktop8:Extension (in Package/Extensions) - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop8-extension)
Uap13 - [uap13:Extension - Windows UWP applications | Microsoft Learn](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-extension)

CHANGED files :
•	ComManifestSchema.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
o	Moved LaunchAndActivationPermissio simple type definition from local to AppxManifestTypes.xsd. No doc change needed.
•	DesktopManifestSchema.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	FoundationManifestSchema.xsd
o	Added reference to already documented schema elements virtualization:FileSystemWriteVirtualization, virtualization:RegistryWriteVirtualization, uap13:AutoUpdate, uap15:DependencyTarget
o	Added uap13:HostRuntimeDependency as child of Package/Dependencies 
o	Added uap11:CurrentDirectoryPath and uap11:Parameters attributes to Application element
•	MobileManifestSchema.xsd
o	Added uap11:ManganeseExtensionAttributesGroup and uap10:TrustLevelGroup
•	RestrictedCapabilitiesManifestSchema.xsd
o	The extension in this schema is currently undocumented (other rescap* extensions are documented). I created a separate work item to track the creation of these docs and I will check it in in a separate PR.
•	RestrictedCapabilitiesManifestSchema_v2.xsd
o	Added uap11:ManganeseExtensionAttributesGroup and uap10:TrustLevelGroup
•	ServerManifestSchema.xsd
o	This is currently undocumented. It has “Preview” throughout the schema doc and it is a lot of content, so I’m not going to document this unless it is requested explicitly.
•	UapManifestSchema.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
o	Added previewappcompat3:Logo: POR is not to document preview namespaces without formal request.
o	Added page for desktop7:ProgId and added it as a child in uap:FileTypeAssociation and uap:Protocol
•	UapManifestSchema_v2.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	UapManifestSchema_v3.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
o	It looks like uap12:Host was added to AppUriHandler, but I’m not seeing that in the current version of the schema, so I assume this change was rolled back. [uapmanifestschema_v3.xsd - Search Code - Search (visualstudio.com)](https://microsoft.visualstudio.com/OS/_search?action=contents&text=uapmanifestschema_v3.xsd&type=code&lp=code-Team&filters=ProjectFilters%7BOS%7DRepositoryFilters%7Bos.2020%7D&pageSize=25&includeFacets=false&result=DefaultCollection/OS/os.2020/GBofficial/main//onecore/printscan/AppxPackaging/Manifest/Schema/2015/UapManifestSchema_v3.xsd)
•	WindowsCapabilitiesManifestSchema_v2.xsd
o	This schema doesn’t appear to be documented publicly. POR is not to document internal namespaces without formal request.
•	DesktopManifestSchema_v2
o	Added uap11:ManganeseExtensionAttributesGroup – Missed this one in the previous pass so I added them.
•	RestrictedCapabilitiesManifestSchema_v3.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	UapManifestSchema_v4.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	WindowsCapabilitiesManifestSchema_v3.xsd
o	The extension defined in this schema is not currently documented. POR is not to document restricted namespaces without formal request.
o	The  InprocMediaCodecAttributes group defined in this file was documented in one of the extensions that referenced it, but it was missing for the other two, so I added the attributes to those extensions.
•	ComManifestSchema_v2.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	DesktopManifestSchema_v3.xsd
o	The Id attribute of the CloudFilesContext menu element was moved from a local type to the AppManifestTypes.xsd schema. Since the attributes were already documented and the type format didn’t change, no doc changes are required.
•	DesktopManifestSchema_v4.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	RestrictedCapabilitiesManifestSchema_v4.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	UapManifestSchema_v5.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
o	The commit shows adding the uap11:Path attribute to the uap5:Host element, but I’m not seeing that in the current version of the schema, so I assume this change was rolled back. [UapManifestSchema_v5.xsd - Repos (visualstudio.com)](https://microsoft.visualstudio.com/OS/_git/os.2020?path=%2Fonecore%2Fprintscan%2FAppxPackaging%2FManifest%2FSchema%2F2017%2FUapManifestSchema_v5.xsd&_a=contents&version=GBofficial%2Fmain)
o	Added uap11:UserConfigurable to uap5:StartupTask.
•	UapManifestSchema_v6.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	DesktopManifestSchema_v6.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
o	Added desktop8:RunAsUser to desktop6:CustomInstall
•	UapManifestSchema_v7.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	UapManifestSchema_v8.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
•	BundleManifestSchema2019.xsd 
o	Added Dependencies element and child TargetDeviceFamily element
•	ComManifestSchema_v3.xsd
o	The LaunchAndActivationPermissionattribute of the com3:ServiceServer element was moved from a local type to the AppManifestTypes.xsd schema. Since the attributes were already documented and the type format didn’t change, no doc changes are required.
•	UapManifestSchema_v10.xsd
o	Added uap11:ManganeseExtensionAttributesGroup – Already did a pass adding these to docs for all extensions that include them
