### ISSUE TITLE
C++/WinRT Inheritance

### ISSUE THREAD

**Issue by EduOak** [MicrosoftDocs/winrt-related#233]
Hi,

I am a pretty C++/WinRT noob and I was asked to author an C++/WinRT API for our internal component testers.

Based on what I've read about WinRT components and inheritance rules I think I am very far away from what I am trying to achieve, so maybe someone more experienced in the matter might help giving me some directions or just saying what I am trying to do is definitely not possible. 

What we are looking for is to have a group of interfaces, a group of base classes that implements or partially implements the interfaces, then a group of specialized classes that extend base classes functionalities.

Here is a brief of the design for interfaces and base classes.

```c++
//ITesterPackage.idl

namespace MyProject
{
    interface ITesterPackage
    {
        String Name{ get; };
    }
}
```
```c++
//TesterPackageBase.idl

import "ITesterPackage.idl";

namespace MyProject
{
    unsealed runtimeclass TesterPackageBase : ITesterPackage
    {
        TesterPackageBase(String Name);
    }
}
```
```c++
//TesterPackageBase.h

namespace winrt::MyProject::implementation
{
    struct TesterPackageBase : TesterPackageBaseT<TesterPackageBase>
    {
    protected:
        hstring _Name;

    public:
        TesterPackageBase() = delete;
        TesterPackageBase(hstring name);

        virtual hstring Name();
    };
}

namespace winrt::MyProject::factory_implementation
{
    struct TesterPackageBase : TesterPackageBaseT<TesterPackageBase, implementation::TesterPackageBase>
    {
    };
}
```
```c++
//TesterPackageBase.cpp

namespace winrt::MyProject::implementation
{
    TesterPackageBase::TesterPackageBase(hstring name)
    {
        _Name = name;
    }

    hstring TesterPackageBase::Name()
    {
        return _Name;
    }
}
```

No issues at this point. However, when trying to derive from TesterPackageBase nothing else seems to work. Compiling after including the below code throws this error:

<b>Error	C2280	'void *winrt::Windows::Foundation::IUnknown::operator new(size_t)': attempting to reference a deleted function</b>

```c++
//Tester1Package.idl

namespace MyProject
{
    [default_interface]
    runtimeclass Tester1Package 
    {
        Tester1Package();
    }
}
```
```c++
//Tester1Package.h

namespace winrt::MyProject::implementation
{
    struct Tester1Package : Tester1PackageT<Tester1Package>, TesterPackageBase
    {
        Tester1Package();
    };
}

namespace winrt::Hp::Bridge::Client::BusinessLogic::AudioNativeBL::factory_implementation
{
    struct Tester1Package : Tester1PackageT<Tester1Package, implementation::Tester1Package>
    {
    };
}
```
```c++
//Tester1Package.cpp

namespace winrt::MyProject::implementation
{
    Tester1Package::Tester1Package() : TesterPackageBase(L"Teste 1")
    {
    }
}
```

Sorry if this is a silly misconception about authoring C++/WinRT APIs. Maybe I am just using my C++ instincts in a wrong direction and mixing different concepts.

Any suggestions?

Thanks in advance.

**Comment by stevewhims** [comment]
Hi, @EduOak, and thanks for filing this issue. Based on the scenario you describe, there's a concept in C++/WinRT of "composition" (which is a way of inheriting from a type). The base type being a "composable class". Here are some pointers to places in the docs that deal with these concepts, in case they help:

* [Deriving from a type that has a non-default constructor](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-apis#deriving-from-a-type-that-has-a-non-default-constructor)
* [Composition and activation](https://docs.microsoft.com/uwp/midl-3/advanced#composition-and-activation)
* Search for "composable class" in [XAML controls; bind to a C++/WinRT property](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-property)

If those don't help, then for questions (or requests for help) regarding your specific scenario, like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

The feedback channel for documentation (**Send feedback about** \> **This page**) is for feedback about the documentation in a particular topic. For example, if you believe that the documentation in a topic is incorrect, or info is missing

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- [The c++-winrt tag on Stack Overflow](https://stackoverflow.com/questions/tagged/c%2b%2b-winrt)

I'll go ahead and close this issue. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Comment by EduOak** [comment]
Hi @stevewhims.

Thank you very much for taking the time to answer. I really appreciate that and for sure I will review the links you pointed me.

Thanks,
-Eduardo
