### ISSUE TITLE
More examples.

### ISSUE THREAD

**Issue by nativenature** [MicrosoftDocs/winrt-related#243]
Please provide more examples for the MIDL newbies.  Also, where there are C# examples it would be nice to also see the C++ and or other languages versions of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82dc10e0-781d-367d-bc47-eef1a4abac87
* Version Independent ID: 4750ae98-e82e-15b7-5f70-c677e051e7ae
* Content: [Synthesizing interfaces (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/synthesizing-interfaces)
* Content Source: [winrt-related-src/midl-3/synthesizing-interfaces.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/synthesizing-interfaces.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by uxdesignbook** [comment]
Hi, @nativenature. Is this issue specifically about the "Synthesizing interfaces" topic? It would help me if you could point to which part(s) of the topic are too thin in terms of examples. Specifically, I'd be interested to know where in the topic you feel that the conceptual content is difficult to understand/follow due to lack of examples.

Also which C# examples were you referring to?

Many thanks!
Steve

**Comment by nativenature** [comment]
The topics of midl aren't so easy to follow for someone new to uwp
programming. Therefore I just would add some more examples.

Personal, I have a c++ background in Linux environments and want to learn
more about Windows Gui programming. The thing is there is little
documentation examples on how to connect sal + midl + xaml + c++. More
examples would clarify why and how to use midl.

Greetings


nativenature

Op ma 28 jun. 2021 23:04 schreef uxdesignbook ***@***.***>:

**Comment by stevewhims** [comment]
Thanks, @nativenature. Have you seen the examples of MIDL in topics such as [XAML controls; bind to a C++/WinRT property](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-property), and [XAML items controls; bind to a C++/WinRT collection](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-collection), and other topics in the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/) documentation? Do those examples/topics help?

Many thanks!
Steve

**Comment by nativenature** [comment]
Hi Steve

Ik have gone briefly over them but it's a lot of explanation. I just miss
the lack of simple examples to make things clearer in general.

Grtz


nativenature


Op wo 30 jun. 2021 03:02 schreef Steven White ***@***.***>:

**Comment by stevewhims** [comment]
Thanks, @nativenature. The examples in those topics around MIDL 3.0 and XAML and C++/WinRT cover the kinds of scenarios people tend to want to do. And the examples are as simple as possible. There are other MIDL examples in other topics in the C++/WinRT content that cover other scenarios.

Since it's not clear what new examples I could add, it's tricky for me to know what to do here. I'll continue to ask around internally about what examples other folks can think of to add. If I hear of any, I'll add them. And if after following along with the existing content (specifically the topics I linked to) you run into scenarios that aren't covered in the documentation, then please let me know and I'll see what I can do to fill the gaps.

Meanwhile I'll close this issue.

Thanks!
Steve
