### ISSUE TITLE
Missing info regarding how ValueName field can be used

### ISSUE THREAD

**Issue by bjr1822** [MicrosoftDocs/winrt-related#26]
An important piece of information that should be explicitly documented is what format the markup should take if you are specifying a default key value (i.e. a value that in .reg format would be named '@'). I ASSUME that I should just leave the ValueName attribute off and provide a Value, but I wonder if instead I should use ValueName="@" or ValueName="" (I assume not the latter because the specification says it must begin and end with a non-whitespace character, and this does neither). Anyway, it's ambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb781ee5-9428-073e-2227-179cd2384503
* Version Independent ID: 865d9dca-6230-5b65-bc71-abe01c8c84e8
* Content: [rescap4:ClassicAppCompatKey - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap4-classicappcompatkey)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-ClassicAppCompatKey.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-ClassicAppCompatKey.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
