### ISSUE TITLE
MIDL 3.0 - Nowhere is "fields" defined.

### ISSUE THREAD

**Issue by marksrasmussen** [MicrosoftDocs/winrt-related#285]
"conceptually similar to fields", 
" unlike fields",  
"Similar to fields and methods"

Nowhere is the term "fields" given any definition.  Is it part of the MIDL 1.0 documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @marksrasmussen! You're right, that isn't clear.

So I've completed a merge to clarify the mention of "fields" in that topic. MIDL 3.0 structs can have fields (or data members). Enums have "constants", which sometimes are referred to as "fields". But I also think that the topic is in places drawing an analogy with C# fields.

In any case, I think I've cleared up the topic now. However, my changes aren't live yet because we have an issue with publishing out of this repo at the moment. So I'll go ahead and close this issue, but I'll continue to actively pursue a fix for that publishing blockage, since it's affecting other of my changes in addition to this one.

Thanks again!
Steve
