### ISSUE TITLE
Please consider using common english when titling sections

### ISSUE THREAD

**Issue by exastone** [MicrosoftDocs/winrt-related#287]
[Enter feedback here]

For the sake of using common language to ensure english literacy doesn't not act as a barrier when searching for documentation, please consider using more common, "plain english" in the future when titling sections, e.g. **Synthesizing** interfaces (MIDL 3.0) becomes **Creating** interfaces (MIDL 3.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82dc10e0-781d-367d-bc47-eef1a4abac87
* Version Independent ID: 4750ae98-e82e-15b7-5f70-c677e051e7ae
* Content: [Synthesizing interfaces (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/synthesizing-interfaces)
* Content Source: [winrt-related-src/midl-3/synthesizing-interfaces.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/synthesizing-interfaces.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @adrwstn, and thanks for filing this issue. You make a very good point, and using simple English is something we'll continue to keep top of mind. It is already part of the guidelines writers are asked to follow.

For this specific case, it's perhaps debatable as to what the right word is. To verify search engine optimization (SEO) behavior, I did a search engine search for `creating interfaces MIDL 3.0`, and I found this topic immediately. I did consider changing "synthesizing" to either "creating" or "authoring", and neither seemed to be objectively better. The MIDL 3.0 compiler doesn't "create" an interface in the sense of *"creating an object of a class"* (since you can't create an instance of an interface), or *"creating a new project in Visual Studio"*. Rather, it does something more akin to "authoring" an interface in the same way a developer would author an interface manually in MIDL 3.0. So it is close to "authoring", but I feel like "authoring" implies human angency. Here, the MIDL 3.0 compiler is synthesizing interfaces (as needed) via a mechanical (or synthetic) process.

The other thing that occurred to me is that the word "analyze" (to break down) is a fairly essential word for a developer to have under their belt; and for that reason it's arguably a word that a writer needn't worry about using and being understood. And "synthesize" (to build up) is simply the converse of that. So I wonder whether "synthesize", too, is a word we needn't worry about using and being understood. But from the description of this issue, it looks like it's less about comprehension and more about the kinds of words that customers would think of to use in search. And, as I say, using `creating interfaces MIDL 3.0` will find the "synthesizing" topic. And using `authoring interfaces MIDL 3.0` will take you to the intro topic, which is exactly where we want folks to start reading, and then they can use the table of contents (TOC) to see the "synthesizing" topic listed out.

I'll go ahead and close the issue, since I don't think there's action to take in this particular case.

Thanks again!
Steve
