### ISSUE TITLE
Usage samples

### ISSUE THREAD

**Issue by JackDetrick** [MicrosoftDocs/winrt-related#30]
Need samples showing reading  and editing of  idl contents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - UWP app developer](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JackDetrick, could you clarify for me, please? Reading and editing of an actual .idl file's contents? Or reading/editing of the generated winmd file? Or something else? As for usage samples, since MIDL 3.0 has its primary use case with the C++/WinRT language projection, you'll find example MIDL 3.0 listings/snippets in the [C++/WinRT docs](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index).

**Comment by stevewhims** [comment]
@JackDetrick, I'll go ahead and close this issue now since it's been a while. Please reopen if I made a mistake in closing. ~Steve
