### ISSUE TITLE
Could use more detail on the desktop2:UseUrl property

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#304]
The only available docs on this say, "If set to true, the file will be opened with the URL path directly".

I _think_ what this is saying is that the app's entry point EXE will be invoked with a URL as a command line argument, if the user is offered a download in Edge that matches this file type, but I'm not entirely sure and the docs don't tell me. When and how exactly is the app invoked, if this property is set to true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10bedc7-7a98-c539-8bb6-cc7d258ec400
* Version Independent ID: f7cde4ec-6c81-bf49-458c-42e8521a1191
* Content: [uap:FileTypeAssociation (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback. The description for this attribute has been updated to provide more useful information:

"If set to true, specifies that the application can accept a URL, instead of a file name, on the command line. Applications that can open documents directly from the internet, like web browsers and media players, should use this value. When ShellExecuteEx starts an application and this value is set to false, the default behavior, ShellExecuteEx downloads the document to a local file and invokes the handler on the local copy."
