### ISSUE TITLE
Unclear docs for uap13:AppInstaller

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#305]
The docs for this element are quite minimal and the description seems inaccurate:

Description: "Specifies a directory containing the installation files for the app."

But the actual element seems to name a file, not a directory: "Specifies the file which should be used to configure auto update settings."

I couldn't find any further information about this element or the uap13 namespace. Obvious questions include:

1. What does it do? Presumably, this is a way for an MSIX package to register itself for auto updates without the user needing to have originally used the .appinstaller file? So the .appinstaller can be bundled, and the user can be directly provisioned with the whole MSIX file for e.g. offline installation? This is a guess.
2. Which versions of Windows support this feature?
3. What happens if the user opens an .appinstaller file that is for the same app as an MSIX using this in the manifest?
4. Is there any way to disable updates for an app that has registered an .appinstaller file in this way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005fc6a6-9327-61b5-7fac-ce77fef2490d
* Version Independent ID: 2488a987-dede-9e52-9054-816599869da5
* Content: [AppInstaller - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-appinstaller)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-appinstaller.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-appinstaller.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching that the content on this page was bad and/or wrong. The descriptions have been updated to correctly describe the elements. Rather than duplicate the details of the AppInstaller file and it's usage, links have been added to [uap13:AppInstaller](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-appinstaller) and [uap13:AutoUpdate](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-autoupdate) pages to point to the full documentation for these features: [Auto-update and repair apps](https://docs.microsoft.com/en-us/windows/msix/app-installer/auto-update-and-repair--overview) and [App Installer file overview](https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-file-overview). These docs have very detailed information about the use of these schema elements. Thanks again for your contribution to the documentation!

**Comment by mikehearn** [comment]
Thanks for the fixes!
