### ISSUE TITLE
Suggested improvements for uap:Logo docs

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#306]
The element hierarchy here has `<uap:Logo>` appearing twice, with `<uap:Protocol>` appearing in the hierarchy but that seems like a copy/paste error. 

The docs imply there's no way to use an .ico file to provide an icon for a file type. Is that really correct? It's either a single size PNG/JPEG or a PRI file and nothing else? I haven't tried using a .ico file yet but it seems odd if Windows no longer supports associating file types with the standard .ico format. It'd be appreciated if someone could double check that.

Also, it doesn't explicitly say anywhere that this is the file type _icon_ (which presumably it is).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2065d35-3628-35ad-342c-68dd7a6f4f62
* Version Independent ID: 71558197-5a45-b7fa-4cbf-2ea50acdcc70
* Content: [uap:Logo (Windows 10, child of uap:FileTypeAssociation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-logo)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-logo.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-logo.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, thanks for calling out this issue with the documentation. For your first issue, the uap:Logo element is a child of both uap:Protocol and uap:FileTypeAssociation. The missing indentation for the element hierarchy makes this hard to decipher, so we have a separate task to update the formatting of the element hierarchy section for all of the schema docs so that the indentation helps to illustrate the relationships better. I don't have an ETA for that fix, but it's in progress.

For the second issue, it turns out that a new element, [desktop7:Logo](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-logo) was introduced to support files with .ico extensions. A page has been created for this element and it has been added to the allowed child elements in the [uap:FileTypeAssociation](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation) element. (desktop7:Logo was not added to uap:Protocol).

Thanks again for your help improving our documentation!
