### ISSUE TITLE
Supported Services

### ISSUE THREAD

**Issue by chipimix** [MicrosoftDocs/winrt-related#31]
Hi!
I have bought a TI CC2650 SensorTag. Using the Bluetooth LE Explorer app from the windows store, I can inspect the service names of my device along with their UUIDs  as well as their characteristics.
Upon inspection, I noticed some service names are named as 5digit numbers (ie: 44032).  

However, as seen [here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-for-bluetooth), only these services are supported.

- name:battery
- name:bloodPressure
- name:cyclingSpeedAndCadence
- name:genericAccess
- name:genericAttribute
- name:glucose
- name:healthThermometer
- name:heartRate
- name:runningSpeedAndCadence

Is it possible to read from services named differently than those from this list?
Thanks!

**Comment by ginami** [comment]
Hi @chipimix -- can you tell me which docs page your question is referring to? This will help me route your comment to the correct author. Thanks!

**Comment by chipimix** [comment]
Hi ginami! https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-for-bluetooth#support-for-bluetooth-gatt-services

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
