### ISSUE TITLE
Desktop10:SupportedProtocols "Key" is not well defined.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#326]
"Key" is not well defined on this page.  I would guess that it is an attribute to desktop10:SupportedProtocols.

Also, it would be helpful to know the purpose of this element.  Is it more like "approved" rather than supported or is this required to integrate protocol handlers into the OS to make them available from outside of the package.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 916b3a5f-c588-5a17-3e83-2b02ba9c0409
* Version Independent ID: 916b3a5f-c588-5a17-3e83-2b02ba9c0409
* Content: [desktop10:SupportedProtocols - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop10-supportedprotocols)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-supportedprotocols.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-supportedprotocols.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
It turns out that "key" was (both in the documentation and the spec the docs were based on) just copied directly from the equivalent registry setting for unpackaged apps in this page: https://learn.microsoft.com/en-us/windows/win32/shell/app-registration

I updated the description to change "key" to "extension" and linked to the app registration page to provide more context. Everything that I have seen indicates that these are indeed supported protocols rather than "approved".
