### ISSUE TITLE
Executable and EntryPoint aren't optional

### ISSUE THREAD

**Issue by anpozd** [MicrosoftDocs/winrt-related#337]
When I don't specify Executable or EntryPoint because they're specified in an enclosing Application, I get the following error.

`
Error | APPX0501 | Validation error. error 80080204: App manifest validation error: Line 39, Column 10, Reason: Extension "windows.service" must declared with "Executable" and "EntryPoint". 
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 687f58a4-2102-25d8-1dc1-8b8257dd45a3
* Version Independent ID: e4a3141a-b214-ce83-bea6-002e8d68e220
* Content: [desktop6:Extension (in Package/Applications) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@anpozd Thanks for catching this. I inquired with the feature owners of this area and it turns out that this is a bug for the windows.service extension. All extensions should allow for these attributes to be omitted and inherit them from the parent Application. A bug has been filed internally to fix this behavior for windows.Service. Thanks again for reporting the issue.
