### ISSUE TITLE
Visibility of call_changed

### ISSUE THREAD

**Issue by Patschkowski** [MicrosoftDocs/winrt-related#339]
observable_vector_base::call_changed has a visibility of protected, observable_map_base::call_changed has a visibility of private. For the map it should be protected as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41fc71b0-c4d5-d85b-65f4-5528072b201a
* Version Independent ID: 03e114a2-a3cd-423f-443a-3f5421af2d6f
* Content: [winrt::observable_map_base struct template (C++/WinRT) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/observable-map-base)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/observable-map-base.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/observable-map-base.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Patschkowski, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic, as published. For example, if the content is incorrect or incomplete.

For questions (or requests for help) about the product itself (C++/WinRT, in this case) one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Or you could use the [`c++-winrt` tag on Stack Overflow](https://stackoverflow.com/questions/tagged/c%2b%2b-winrt) to report the issue.

Or you could try contributing a change to the [The C++/WinRT language projection](https://github.com/microsoft/cppwinrt) GitHub repo.

Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll close this issue, though, since it doesn't look like an issue with the documentation.

Thanks!
-Steve
