### ISSUE TITLE
where is `api-ms-win-core-com-l1-1-0.dll`?

### ISSUE THREAD

**Issue by hyqhero** [MicrosoftDocs/winrt-related#348]
Why didn't I find api-ms-win-core-com-l1-1-0.dll in Windows kits/10/Redist/ucrt/Dlls/x64 after installing Windows SDK (10.0.16299.91) or (10.0.10240)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8b23f4-f83b-e5fb-076b-f58e7fa8ec5b
* Version Independent ID: 20a237ef-9a49-1786-f00a-df422f8f07bb
* Content: [APIs present on all Windows 10 devices (grouped by module) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-core-com-l1-1-1dll)
* Content Source: [winrt-related-src/win32-and-com/win32-apis.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/win32-and-com/win32-apis.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @hyqhero, and thanks for filing this issue.

It's by design that you won't find `api-ms-win-core-com-l1-1-0.dll` in that folder.

`api-ms-win-core-com-l1-1-0.dll` is an API set. And API sets are normally not shown as files in the file system (although it depends on which OS version you're looking on). This topic is documenting Windows 10 and above, so these API sets will just inherently be available to all applications at runtime. No `.dll` file is needed for them; they're simply built into the loader. But the API set *is* available, via its name, and it works just as if it were a physical .dll file in the system.

Thanks!
-Steve

**Comment by hyqhero** [comment]
Thank you for your answer!
 but I now hope to use some APIs in this DLL on Win7, so is it necessary to include a. dll file?

**Comment by hyqhero** [comment]
> Hi, @hyqhero, and thanks for filing this issue.
> 
> It's by design that you won't find `api-ms-win-core-com-l1-1-0.dll` in that folder.
> 
> `api-ms-win-core-com-l1-1-0.dll` is an API set. And API sets are normally not shown as files in the file system (although it depends on which OS version you're looking on). This topic is documenting Windows 10 and above, so these API sets will just inherently be available to all applications at runtime. No `.dll` file is needed for them; they're simply built into the loader. But the API set _is_ available, via its name, and it works just as if it were a physical .dll file in the system.
> 
> Thanks! -Steve

Thank you for your answer!
but I now hope to use some APIs in this DLL on Win7, so is it necessary to include a. dll file?
