### ISSUE TITLE
some dll can not be found on windows 7. please help.

### ISSUE THREAD

**Issue by hyqhero** [MicrosoftDocs/winrt-related#362]
api-ms-win-core-winrt-l1-1-0.dll
api-ms-win-core-winrt-string-l1-1-0.dll
api-ms-win-shcore-scaling-l1-1-1.dll
api-ms-win-power-base-l1-1-0.dll
api-ms-win-power-string-l1-1-0.dll

The above libraries are not available on Windows 7, and the download page cannot be found on Microsoft's official website. Where can I download them? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8b23f4-f83b-e5fb-076b-f58e7fa8ec5b
* Version Independent ID: 20a237ef-9a49-1786-f00a-df422f8f07bb
* Content: [APIs present on all Windows devices - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/win32-and-com/win32-apis)
* Content Source: [winrt-related-src/win32-and-com/win32-apis.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/win32-and-com/win32-apis.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**
```[tasklist]
### Tasks
```

**Comment by stevewhims** [comment]
Hi, and sorry for my delay in responding! Those look like the names of API sets, rather than DLLs. API sets have names, and those names often have ".dll" appended to them so that the DLL loader can do its magic (via LoadLibrary). However, the actual dll that's loaded for an API set name varies by operating system version, and is likely not to have the same name as the API set. For full details on this, please see [Windows API sets](https://learn.microsoft.com/windows/win32/apiindex/windows-apisets). There's a link to that from the topic in question.

Thanks!
-Steve
