### ISSUE TITLE
Default value not given for optional boolean parameter

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#375]
On both Uap2:Verb and Uap3:Verb documentation there is an optional boolean value named "Default", which indicates whether the verb is the default shell command for the supported file type.  

In the documentation, no default value is defined, leaving one to wonder what happens if the parameter is not expressed.

I would guess that not expressing the parameter *should* mean the same as default=no, but it really should be defined here.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b826703-042f-7cf4-6973-20923b1373d7
* Version Independent ID: b18204a7-4920-8d16-3d05-60ea49a4a8db
* Content: [uap3:Verb - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-verb)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-verb.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-verb.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I traced through the source code for this and there's not *really* a default value. The code only sets the default if the value is present. Since this is functionally similar to there being a default value, I went ahead and specified that the default value is false. During this investigation I noticed that the code throws an error if there is already a default verb set, so I added that to the description as well "Only one verb within SupportedVerbs can be set as the default verb."
