### ISSUE TITLE
<uap5:Extension Category="windows.startupTask" uap10:Parameters="--Source=Auto --Activate=False"> does not work on Windows 10

### ISSUE THREAD

**Issue by JiangYi11111111** [MicrosoftDocs/winrt-related#376]
I use "uap10:Parameters" to pass parameters to my App when it is started in case of user login.
These parameters can be passed to App on Windows 11. But it does not work on Windows 10 (22H2 - build 19045.3448).

<uap5:Extension Category="windows.startupTask" uap10:Parameters="--Source=Auto --Activate=False">

**Comment by drewbatgit** [comment]
Hello, we recently added OS version support information to all of the package schema documentation. This information wasn't yet in the page when you opened this issue. It looks like the uap10 schema was introduced in Windows 10 version 2004 (Build 19041), so if the version you are testing on is earlier than that, then this is expected behavior. If you are seeing this on build 19041 or later, then I recommend you open an issue on [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) for technical help.
