### ISSUE TITLE
Namespace for the Extension element

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#380]
Please add to the documentation, information that when the Category is associated with a child that uses an non-foundation category/child element, the Extension element should be issued with the namespace associated with the child element namespace (associated with the category).  This might be confusing to explain, in which case an example would be helpful.

For example:

<Extensions>
   <uap6:Extension Category="windows.loaderSearchPathOverride">
      <uap6:LoaderSearchPathOverride>
           ...
      </uap6:LoaderSearchPathOverride>
   </uap6:Extension Category="windows.loaderSearchPathOverride">
</Extensions>

In addition to updating the package Extension element page, you might earn bonus points if the child element pages down the stack are updated too!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62762880-6dfc-c9a0-f040-92a359de913e
* Version Independent ID: 47f6f79b-4c35-9075-c566-3eeda412ba1f
* Content: [Extension (in Package/Extensions) (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I'm not sure I'm following what you are requesting here Tim. Your example isn't rendering.  Can you please clarify what you are suggesting?

**Comment by TimMangan** [comment]
I told you it was confusing!

For example.  Let's say that I want to add an extension using the uap6:LoaderSearchPathOverride child element.  That means that the extension also needs to be uap6, as in...

<Uap6:Extension Category="windows.loaderSearchPathOverride">
    <Uap6:LoaderSearchPathOverride ... />
</Uap6:Extension>

I am GUESSING that this isn't true if the extension uses a parameter like desktop:Scope.

**Comment by drewbatgit** [comment]
@TimMangan Hmm, this seems like something that is just intrinsic to XML. The element Extension is a different element than the uap6 extension. They just happen to have the same name. If you declare your element as `<Extension>` rather than `<uap6:Extension>` then the category name is invalid because "windows.loaderSearchPathOverride" isn't a valid value for Extension element defined in the http://schemas.microsoft.com/appx/manifest/foundation/windows10 namespace. It seems like  the thing that makes this a little confusing is that the foundation namespace is the global namespace in the app manifest document and so it is the one element that doesn't require a disambiguating prefix.

I think for now, I'm going to close this issue as a "won't fix" because, as we have seen here, it's hard to explain the concept and I haven't seen any comments from users who are confused about this, so we don't want to *introduce* confusion. If you feel strongly this is needed for developers to package their apps successfully, feel free to keep the conversation going in the comments.

**Comment by drewbatgit** [comment]
One other thing that occurs to me is that, although it sounds like a total nightmare, it seems like people could map namespaces to different prefixes than the default app manifest file. For example, I could declare the global namespace to be:

`xmlns="http://schemas.microsoft.com/appx/manifest/uap/windows10/6"`

And then declare a new prefix:

"xmlns:found="http://schemas.microsoft.com/appx/manifest/foundation/windows10"`

As long as I updated the prefixes on all of the elements accordingly, this would still be correct, right? You would have to really enjoy pain to do something like that, but if the manifests are standardized xml, I would think it would work.

**Comment by TimMangan** [comment]
Well, it is more intrinsic to how these schemas were written, but the schema set isn't going to change... I think it's still going to confuse folks (I lost a few hours on this and I _think_ I know this stuff), but I'm OK with closing this.

As to declaring by using a different prefix, yes it should work -- but in reality, is a **really** bad thing to do because you are depending on so many tools and if only one of them hard coded the prefix you loose.
