### ISSUE TITLE
Reversed UsagePage and UsageId in the examples

### ISSUE THREAD

**Issue by gabrielboroghina** [MicrosoftDocs/winrt-related#44]
Hi! In the code snippets above, for gamepad and joystick, the UsagePage and UsageId should be reversed in the &lt;Function&gt; tag (so that to follow the format usage:"UsagePage UsageId"). More exactly, for a gamepad, the Type should be usage:"0x0001 0x0005" (or usage:"0x0001 *" if using the format from the examples). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce31bbb-4767-a12d-d68b-2aa2e9ceafca
* Version Independent ID: c43a6140-b635-46b6-3e7d-7a1e48e62ea3
* Content: [How to specify device capabilities for HID - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-for-hid)
* Content Source: [winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-for-hid.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-for-hid.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
