### ISSUE TITLE
Is it BundleManifest.xml or AppxBundleManifest.xml?

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-related#55]
this page mentions BundleManifest.xml as the name of the file in the .appxbundle but I understand AppxBundleManifest.xml is the right name. please update this page if I have this right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 430cf11d-6135-54ef-58b4-2911a75c08ed
* Version Independent ID: d5f28c9e-3d06-6c74-8519-c40797c3cfa8
* Content: [Bundle manifest - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/bundlemanifestschema/bundle-manifest)
* Content Source: [winrt-related-src/schemas/bundlemanifestschema/bundle-manifest.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/bundlemanifestschema/bundle-manifest.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
