### ISSUE TITLE
this schema is stored in AppxManifest.xml files in the .appx file and files with .appxmanifest in source

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-related#56]
This page should explain the names of the files and file extension used to identify files that contain xml that follows this schema to make it easier to relate those files and this documentation. For example in the .appx file this schema is stored in a file named AppxManifest.xml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b26b439-4abf-bfd7-681c-51930f503e88
* Version Independent ID: 4d8d1692-44a6-0531-8277-923125eb57eb
* Content: [App package manifest - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appx-package-manifest)
* Content Source: [winrt-related-src/schemas/appxpackage/appx-package-manifest.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/appx-package-manifest.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
