### ISSUE TITLE
MainPackageDepencency is not documented, part of optional packages/related sets

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-related#57]
I found searching for "MainPackageDependency" from https://docs.microsoft.com/en-us/windows/uwp/packaging/ does not produce any results.

But I did find this documented here: https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-mainpackagedependency-manual 

Seems the index needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c20a74-18a7-a0a3-b828-6d2749151255
* Version Independent ID: 1ac0dc95-48ec-4a3b-4455-b8a0b6f094b2
* Content: [Package manifest schema reference for Windows 10 - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md)
* Product: **windows**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
