### ISSUE TITLE
Moving the NavigationView to another Frame makes it unresponsive.

### ISSUE THREAD

**Issue by frankthvandeven** [MicrosoftDocs/winrt-related#77]
I am using the build 17134 SDK, but the latest Microsoft.UI.XAML 2.0.181018003.1 has the same problem.

When moving the NavigationView to another Frame, the NavigationView menu items cannot be clicked anymore. This means that giving the NavigationView another parent control upsets it. Hovering over menu items still works as I can see the color change.

object temp = Frame1.Content; // content is the NavigationView
Frame1.Content = null;
Frame2.Content = temp;

The problem is odd as other controls can be moved to another Frame without problems. 

Placing the NavigationView inside a Grid (for example) does not solve the problem. I also tried placing it in a Grid and do a Grid.Children.Remove() before adding it to another Grid, but also not a solution.

[NavigationViewPanelTest.zip](https://github.com/MicrosoftDocs/winrt-related/files/2708358/NavigationViewPanelTest.zip)

**Comment by frankthvandeven** [comment]
I also added this issue to GitHub Microsoft/microsoft-ui-xaml as issue #137

**Comment by ginami** [comment]
Hi @frankvandeven -- I'm sorry you're experiencing this problem. This issue list is for feedback on specific docs rather than general dev issues. Is this related to one of our docs? If not, I'd recommend reposting on one of the forums, or User Voice, both of which are linked from our support page (https://developer.microsoft.com/en-us/windows/support.)
If this is directly related to one of our docs, please provide the URL and I'll route your feedback to the correct author.
Thank you!!!
