### ISSUE TITLE
app manifest references the splash screen image 'assets\splash-sdk.png' which does not have valid dimensions. it must be 620x300 pixels.

### ISSUE THREAD

**Issue by c-don** [MicrosoftDocs/winrt-related#84]
I am getting the above error even though I have splash-sdk png file in the asset folder that has the dimensions 620x300. I am not sure how to fix this issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce789828-b3a9-a413-34d1-e9965f4ff885
* Version Independent ID: d366fc7a-e829-66c4-98e2-c05e0a4040b6
* Content: [uap:SplashScreen (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-splashscreen)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-splashscreen.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-splashscreen.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
