### ISSUE TITLE
toast element is missing documentation for the displayTimestamp attribute.

### ISSUE THREAD

**Issue by jlaanstra** [MicrosoftDocs/winrt-related#93]
The displayTimestamp attribute is listed at https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts#custom-timestamp, but not documented as part of the schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a9d44e-b5d2-9da9-1d9a-d2450b549572
* Version Independent ID: 3fc3283d-fe01-5536-3e31-e1213fae3ad5
* Content: [toast - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-toast)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/element-toast.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/element-toast.md)
* Product: **uwp**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
