### ISSUE TITLE
This schema is out of date.

### ISSUE THREAD

**Issue by rawlinson** [MicrosoftDocs/winrt-related#94]
It is missing several elements and attributes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fff893d-cf72-dbef-92c1-9ea3bc37d8f4
* Version Independent ID: f5676d7c-7ca0-d9f9-89ba-1339e82db0cd
* Content: [Toast schema - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/schema-root)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/schema-root.md)
* Product: **uwp**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
