### ISSUE TITLE
AutomaticBackgroundTask & ForceUpdateFromAnyVersion

### ISSUE THREAD

**Issue by driesvandamme** [MicrosoftDocs/winrt-related#95]
ForceUpdateFromAnyVersion & AutomaticBackgroundTask can't be used in combination?

When using AutomaticBackgroundTask (and triggering it by running the Scheduled task taking care of it) it doesn't take lower versions into account. Only when a higher version was published, it downloads & installs the update...

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ce7ce943-631c-600e-c5ef-7ecd95f70aeb
* Version Independent ID: 95c6d06d-92c3-8900-e44f-8300644f12ee
* Content: [UpdateSettings - Windows UWP applications](https://docs.microsoft.com/nl-nl/uwp/schemas/appinstallerschema/element-update-settings)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-update-settings.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-update-settings.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
